# Generated by Django 3.1.3 on 2023-01-17 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0002_auto_20230117_0952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='chocies',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='enrollment',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Submission',
        ),
    ]
