# Generated by Django 3.1.3 on 2023-01-17 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0006_auto_20230117_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='choice_text',
            field=models.CharField(default='string', max_length=66),
            preserve_default=False,
        ),
    ]
